(cram
 (deps
  (package yamlt)
  (glob_files ../data/scalars/*.yml)
  (glob_files ../data/scalars/*.json)
  (glob_files ../data/objects/*.yml)
  (glob_files ../data/objects/*.json)
  (glob_files ../data/arrays/*.yml)
  (glob_files ../data/arrays/*.json)
  (glob_files ../data/formats/*.yml)
  (glob_files ../data/formats/*.json)
  (glob_files ../data/complex/*.yml)
  (glob_files ../data/complex/*.json)
  (glob_files ../data/edge/*.yml)
  (glob_files ../data/edge/*.json)
  (glob_files ../data/locations/*.yml)))
